version: 0.2
phases:
  pre_build:
    commands:

      - aws --version
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 339712795299.dkr.ecr.ap-south-1.amazonaws.com
      - echo Setting Repo URI...
      - REPOSITORY_URI=339712795299.dkr.ecr.ap-south-1.amazonaws.com/nagp_ecom_application
      - echo declaring image tag
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker-compose build   
      - echo Listing Docker images...
      - docker images      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker-compose push
      - echo Listing Docker images after push...
      - docker images
      - echo Writing image definitions file...
      - printf '[{"name":"nagp_ecom_application","imageUri":"%s"}]' $REPOSITORY_URI:user-service  > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json