version: '3.8'

services:
  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      product-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  cart-service:
    build: 
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      product-service:
        condition: service_healthy
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
networks:
  ecom-network:
    driver: bridge
