volumes:
  userapp:
  productapp:
  orderapp:

services:
  user-service:
    container_name: user-service-c
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: 339712795299.dkr.ecr.ap-south-1.amazonaws.com/nagp_ecom_application:user-service-latest 
    ports:
      - "5001:5001"
    restart: always

  product-service:
    container_name: product-service-c
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: 339712795299.dkr.ecr.ap-south-1.amazonaws.com/nagp_ecom_application:product-service-latest  
    ports:
      - "5002:5002"
    restart: always

  order-service:
    container_name: order-service-c
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: 339712795299.dkr.ecr.ap-south-1.amazonaws.com/nagp_ecom_application:order-service-latest  
    ports:
      - "5003:5003"
    restart: always
