version: "3.8"

volumes:
  userapp:
  productapp:
  orderapp:

services:
  user-service:
    container_name: user-service-c
    image: 339712795299.dkr.ecr.ap-south-1.amazonaws.com/nagp_ecom_application/user-service:latest 
    ports:
      - "5001:5001"
    volumes:
      - userapp:/userapp
    restart: always

  product-service:
    container_name: product-service-c
    image: 339712795299.dkr.ecr.ap-south-1.amazonaws.com/nagp_ecom_application/product-service:latest  
    ports:
      - "5002:5002"
    volumes:
      - productapp:/productapp
    restart: always

  order-service:
    container_name: order-service-c
    image: 339712795299.dkr.ecr.ap-south-1.amazonaws.com/nagp_ecom_application/order-service:latest  
    ports:
      - "5003:5003"
    volumes:
      - orderapp:/orderapp
    restart: always
