version: '3.8'

services:
  product-service:
    volumes:
      - ./product-service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # Local OpenSearch settings if needed
      - OPENSEARCH_HOST=localhost
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USE_SSL=false

  user-service:
    volumes:
      - ./user-service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # Local database settings if needed
      - DB_HOST=localhost
      - DB_PORT=5432

  order-service:
    volumes:
      - ./order-service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  cart-service:
    volumes:
      - ./cart-service:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
