volumes:
  userapp:
  productapp:
  orderapp:

services:
  user-service:
    container_name: user-service-c
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user-service:latest 
    ports:
      - "5001:5001"
    restart: always

  product-service:
    container_name: product-service-c
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: product-service:latest  
    ports:
      - "5002:5002"
    restart: always

  order-service:
    container_name: order-service-c
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: order-service:latest  
    ports:
      - "5003:5003"
    restart: always
